---
    - hosts: all
      become: true
      tasks:

       - name: update
         become_user: root
         yum:  
           name: '*'
           state: latest

       - name: "Install gluster"
         become_user: root
         yum:
           name: centos-release-gluster
       
       - name: "Install glusterfs"
         become_user: root
         yum:
           name: glusterfs-server

       - name: start gluster
         shell: sudo systemctl start glusterd
         become: yes

       - name: "Add nodes"
         become_user: root
         shell: echo "192.168.33.100	master" >> /etc/hosts && echo "192.168.33.11	worker-1" >> /etc/hosts && echo "192.168.33.12	worker-2" >> /etc/hosts && echo "192.168.33.13	worker-3" >> /etc/hosts
         become: yes 
      
       - name: "install Docker"
         become_user: root
         yum:
          name: docker
          state: present
          update_cache: true

       - name: "Start Docker"
         service:
           name: docker
           state: restarted
           enabled: yes

       - name: "Add docker permisions to vagrant"
         shell: usermod -aG dockerroot vagrant
         become: yes 
   
       - name: "Install Docker Compose"
         get_url:
           url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
           dest: "/usr/bin/docker-compose"
           mode: 0755

       - name: "stop of firewall"
         shell: systemctl stop firewalld
         
       - name: "disable the firewall"
         shell: systemctl disable firewalld
